apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: prometheus-lab
data:
  alert.rules: |
    groups:
    - name: example
      rules:
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: "Memory usage is above 80% for more than 2 minutes"
      
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Pod is crash looping
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently"
