kind: LDAPSyncConfig
apiVersion: v1
url: ldap://ldap.example.com:389
bindDN: "cn=admin,dc=example,dc=com"
bindPassword: admin123
insecure: true
groupUIDNameMapping:
  "cn=developers,ou=groups,dc=example,dc=com": developers
  "cn=admins,ou=groups,dc=example,dc=com": admins
  "cn=viewers,ou=groups,dc=example,dc=com": viewers
rfc2307:
  groupsQuery:
    baseDN: "ou=groups,dc=example,dc=com"
    scope: sub
    derefAliases: never
    filter: (objectClass=groupOfNames)
    pageSize: 0
  groupUIDAttribute: dn
  groupNameAttributes: [ cn ]
  groupMembershipAttributes: [ member ]
  usersQuery:
    baseDN: "ou=users,dc=example,dc=com"
    scope: sub
    derefAliases: never
    filter: (objectClass=inetOrgPerson)
    pageSize: 0
  userUIDAttribute: dn
  userNameAttributes: [ uid ]
  tolerateMemberNotFoundErrors: false
  tolerateMemberOutOfScopeErrors: false
