apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-prod

resources:
- ../../applications/sample-app

patchesStrategicMerge:
- replica-patch.yaml

commonLabels:
  environment: prod
