apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../app-config

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

namePrefix: prod-
commonLabels:
  environment: production
