apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: lab-prometheus
  namespace: alerting-lab
spec:
  replicas: 1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      app: resource-test-app
  ruleSelector:
    matchLabels:
      prometheus: kube-prometheus
      role: alert-rules
  alerting:
    alertmanagers:
    - namespace: alerting-lab
      name: alertmanager
      port: web
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
  retention: 24h
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
